
services:

  reddit-consumer:
    build:
      context: .
      dockerfile: ./src/services/consumers/reddit/Dockerfile
    container_name: reddit-consumer

  reddit-scrapper:
    build:
      context: .
      dockerfile: ./src/services/scrappers/reddit/Dockerfile
    container_name: reddit-scrapper

  youtube-consumer:
    build:
      context: .
      dockerfile: ./src/services/consumers/youtube/Dockerfile
    container_name: youtube-consumer

  youtube-scrapper:
    build:
      context: .
      dockerfile: ./src/services/scrappers/youtube/Dockerfile
    container_name: youtube-scrapper

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  default:
    name: estudart-sentiment-data-collector
    driver: bridge
